site_name: Connected Health
site_url: https://connectedhealth.group
#site_description: Add description for website (good for SEO)
#copyright: Add copyright info here if needed

# Below is the navigation bar. To add a new page, create a new markdown file in the docs folder and link to it here.
# You can also create subpages by indenting the links under a parent page (e.g. just like in the About section).
nav:
  - Home: 'index.md'
  - About: 
    - 'about/index.md'
    - Meet the Team: 'about/team.md'

# Site configuration
theme:
  name: material
  language: en
  font:
    text: 'Inter'
  #favicon: assets/favicon.png
  logo: assets/logo.png
  palette:
    scheme: default
    primary: '#58064E'
    accent: '#9A2E4F'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - content.tabs.link
    - content.tabs
    - navigation.path
    - navigation.top

# If you want to add custom css, create a stylesheets folder in the docs/ directory and add your css file there.
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - assets/js/team.js
  
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.blocks.caption
  - footnotes
  - abbr
  - pymdownx.snippets:
      check_paths: True

plugins:
  - glightbox
  - search
  - tags
