site_name: SysteMatic
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - 'Design Cooperative':
    - 'Design Cooperative 0.1': 'design-cooperative/design-coop1.md'
    - 'People Insights': 'design-cooperative/people-insights.md'
    - 'Health Intelligence': 'design-cooperative/health-intelligence.md'
    - 'Systems Futures': 'design-cooperative/systems-futures.md'
  - 'Key Populations':
    - 'Children and Families': 'key-populations/children-and-families.md'
    - 'Working Lives': 'key-populations/working-lives.md'
    - 'Pre-Frailty': 'key-populations/pre-frailty.md'
  - Systems Innovation: 'systems-innovation.md'
  - Living Library: 'living-library.md' 
  - Partners: 'partners.md'
theme:
  name: material
  palette:
    scheme: systematic
  logo: assets/3d-logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - content.tabs
    - navigation.path
extra_css:
  - stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - glightbox
  - search
