site_name: SysteMatic
nav:
  - Home: 'index.md'
  - 'Design Cooperative':
    - 'Design Cooperative 0.1': 'design-cooperative/design-coop1.md'
    - 'Public Involvement': 'design-cooperative/public-engagement.md'
    - 'How we use data': 'design-cooperative/how-we-use-data.md'
  - About: 'about.md'
theme:
  name: material
  palette:
    scheme: systematic
  logo: assets/logo-notext.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - content.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - glightbox
