site_name: SysteMatic
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Partners: 'partners.md'
  - Knowledge Commons: 'digital-commons.md' 
  - Glossary: 'glossary.md'
  - 'Design Co-operative':
    - 'Overview': 'design-cooperative/overview.md'
    - 'People Insights': 'design-cooperative/people-insights.md'
    - 'Health Intelligence': 'design-cooperative/health-intelligence.md'
    - 'Systems Futures': 'design-cooperative/systems-futures.md'
  - Key Populations:
    - 'Overview': 'key-populations/overview.md'
    - 'Children and Families': 'key-populations/children-and-families.md'
    - 'Working Lives': 'key-populations/working-lives.md'
    - 'Pre-Frailty': 'key-populations/pre-frailty.md'
  - Systems Science: 
    - 'Overview': 'systems-science/overview.md'
    - 'Systems Optimisation': 'systems-science/optimisation.md'
    - 'Systems Innovation': 'systems-science/innovation.md'
    - 'Systems Transition': 'systems-science/transition.md'
  
theme:
  name: material
  palette:
    scheme: systematic
  logo: assets/3d-logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - content.tabs
    - navigation.path
extra_css:
  - stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - search
