site_name: SysteMatic Digital Commons

copyright: Copyright &copy; 2024 SysteMatic Project

nav:
  - Home: 'index.md'
  - About: 
    - 'about/index.md'

  
theme:
  name: material
  # Add 
  # logo: 'assets/logo.png'
  palette:
    scheme: systematic
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - content.tabs.link
    - content.tabs
    - navigation.path
    - navigation.top
    
extra_css:
  - stylesheets/extra.css
  
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.blocks.caption
  - footnotes
  - abbr
  - pymdownx.snippets:
      check_paths: True

plugins:
  - glightbox
  - search
  - tags
