site_name: SysteMatic Digital Commons
nav:
  - Home: 'index.md'
  - About: 
    - 'about-systematic/index.md'
    - Developing SysteMatic: 'about-systematic/development-stage.md'
    - Navigating the Commons: 'about-systematic/commons-structure.md' 
  - Health Intelligence: 
    - 'health-intelligence/index.md'
  - People Insights: 
    - 'people-insight/index.md'
    - Qualitative data collection: 'people-insight/qualitative-data-collection.md'
    - MLTC activity book: 'people-insight/activity-book.md'
    - Metaphors of MLTC lived experience: 'people-insight/metaphors.md'
    - Person maps: 'people-insight/person-maps.md'
    - MLTC journeys map: 'people-insight/journey-maps.md'
    - MLTC system problems map: 'people-insight/system-maps.md'
    - MLTC systems actor map: 'people-insight/actor-map.md'
  - Systems Science: 
    - 'systems-science/index.md'
  - Collective Synthesis & Outcomes:
    - 'collective-outcomes/index.md'
    - Big & thick data: 'collective-outcomes/big-thick-data.md' 
    - Problem definition: 'collective-outcomes/problem-definition.md'
    - Problem prioritisation: 'collective-outcomes/problem-prioritisation.md'
    - MLTC learning system framework: 'collective-outcomes/MLTC-learning-system-framework.md'
  - Glossary: 'glossary.md'
  
theme:
  name: material
  logo: 'assets/logo.png'
  palette:
    scheme: systematic
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - content.tabs.link
    - content.tabs
    - navigation.path
    - navigation.top
extra_css:
  - stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - search
  - tags:
      tags_file: tags.md
