h site_name: SysteMatic Digital Commons
nav:
  - Home: 'index.md'
  - About SysteMatic: about.md
  - Health Intelligence: 
    - health-intelligence/index.md
  - People Insights: 
    - people-insight/index.md
  - Systems Science: 
    - systems-science/index.md
  - Collective Synthesis & Outcomes:
    - collective-outcomes/index.md
  - Glossary: glossary.md
  
theme:
  name: material
  logo: 'assets/logo.png'
  palette:
    scheme: systematic
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - content.tabs.link
    - content.tabs
    - navigation.path
    - navigation.top
extra_css:
  - stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - search
