site_name: SysteMatic Digital Commons

copyright: Copyright &copy; 2024 SysteMatic Project

nav:
  - Home: 'index.md'
  - About: 
    - 'about-systematic/index.md'
    - SysteMatic development phase: 'about-systematic/development-stage.md'
    - Navigating the Commons: 'about-systematic/commons-structure.md' 
  - Health Intelligence: 
    - 'health-intelligence/index.md'
  - People Insights: 
    - 'people-insight/index.md'
    - Public involvement: 'people-insight/public-involvement.md'
    - MLTC activity books: 'people-insight/activity-book.md'
    - Metaphors: 'people-insight/metaphors.md'
    - Systemic people stories: 'people-insight/systemic-stories.md'
    - MLTC systems actor map: 'people-insight/actor-map.md'
  - Systems Science: 
    - 'systems-science/index.md'
    - 3 orders of MLTC systems science: 'systems-science/orders.md'
  - Transdisciplinary Synthesis & Strategy:
    - 'collective-outcomes/index.md'
    - Problem definition: 'collective-outcomes/problem-definition.md'
    - Problem prioritisation: 'collective-outcomes/problem-prioritisation.md'
    - Stage 2 report: 'collective-outcomes/stage-2-report.md'
    - Sandpit report: 'collective-outcomes/sandpit-report.md'
    - MLTC learning system framework: 'collective-outcomes/MLTC-learning-system-framework.md'
  - Glossary: 'glossary.md'
  
theme:
  name: material
  logo: 'assets/logo.png'
  palette:
    scheme: systematic
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - content.tabs.link
    - content.tabs
    - navigation.path
    - navigation.top
    
extra_css:
  - stylesheets/extra.css
  
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.blocks.caption

plugins:
  - glightbox
  - search
  - tags:
      tags_file: tags.md
