# name: Build & deploy
# on:
#   push:
#     branches:
#       - master
#       - main
# permissions:
#   contents: write
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v4
#         with:
#           python-version: "3.11.5"
#       - run: pip install uv
#       - run: uv sync
#       - run: uv run mkdocs build
#       - run: uv run mkdocs gh-deploy --force
